site_name: AskOmics
repo_url: https://github.com/askomics/flaskomics
edit_uri: edit/master/docs/
site_author: Xavier Garnier

theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - javascript
markdown_extensions:
  - admonition
  - fontawesome_markdown
  - toc:
      permalink: true
      toc_depth: 1


nav:
  - Home: index.md
  - AskOmics tutorials:
    - Overview tutorial: tutorial.md
    - Prepare data: data.md
    - Build RDF Abstraction: abstraction.md
    - Federated queries: federation.md
    - AskOmics and Galaxy: galaxy.md
    - Contribute: issues.md
  - Admin :
    - Deploy AskOmics: production-deployment.md
    - Configure: configure.md
  - Developer guide:
    - Deploy AskOmics: dev-deployment.md
    - Contribute: contribute.md
    - CI: ci.md
    - Doc: doc.md
  - Bug Tracker: https://github.com/askomics/flaskomics/issues
  - Project monitoring: https://github.com/askomics/flaskomics/projects

extra_css: [style.css]
